### ISSUE TITLE
使用了插件springboot无法启动

### ISSUE THREAD

**Issue by maodouzi123** [houxinlin/cool-request#116]
插件版本：2024.10.15
springboot版本：1.5.14.RELEASE

启动就报错：Application startup failed
java.lang.AbstractMethodError: null
	at org.springframework.boot.SpringApplicationRunListeners.callFinishedListener(SpringApplicationRunListeners.java:79)
	at org.springframework.boot.SpringApplicationRunListeners.finished(SpringApplicationRunListeners.java:72)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:305)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	at cn.expsoft.AppMain.main(AppMain.java:13)

**Comment by houxinlin** [comment]
springboot版本太低了，有个抽象方法没有实现，在cool requets设置里，第一个选择，关闭高级特性就可以了

**Comment by maodouzi123** [comment]
可以启动了，感谢解答。
