### ISSUE TITLE
在function中自定义方法，调用后报错

### ISSUE THREAD

**Issue by yhl1314** [houxinlin/cool-request#128]
使用自定义方法，有时候正常有时候报错，方法仿造demo中写的
IDEA版本：IntelliJ IDEA 2024.2.3 (Ultimate Edition)
![image](https://github.com/user-attachments/assets/3dc28841-2510-46aa-8413-b4c74ea9b128)
![image](https://github.com/user-attachments/assets/93baad7a-8046-4204-8ec0-ad2f8ac5f897)

异常日志：
2024-12-06 15:33:19,635 [20228830]   INFO - #c.i.o.p.u.AbstractProgressIndicatorBase - This progress indicator (Cool request 1779797713: running=true; canceled=false; task=com.cool.request.components.http.net.RequestManager$HTTPRequestTaskBackgroundable@22cab97a) is indeterminate, this may lead to visual inconsistency. Please call setIndeterminate(false) before you start progress. class com.intellij.openapi.progress.impl.BackgroundableProcessIndicator
java.lang.IllegalStateException
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.setFraction(AbstractProgressIndicatorBase.java:211)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.setFraction(AbstractProgressIndicatorExBase.java:119)
	at com.intellij.openapi.progress.util.ProgressWindow.setFraction(ProgressWindow.java:333)
	at com.cool.request.components.http.net.RequestManager.updateProgressIndicator(RequestManager.java:80)
	at com.cool.request.components.http.net.RequestManager$HTTPRequestTaskBackgroundable.run(RequestManager.java:230)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:477)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:528)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:249)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:221)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:49)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:220)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:202)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:249)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:501)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:466)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:92)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:92)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:97)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:92)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$19(ProgressRunner.java:464)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by yhl1314** [comment]
使用自定义方法压测偶然发生，替换成内置的randomPassword也会出现
![image](https://github.com/user-attachments/assets/0c5ec991-edaf-419d-bf12-08361b5be700)

**Comment by houxinlin** [comment]
好的，等修复

**Comment by houxinlin** [comment]
没有复现，我发现失败的都是没有message参数的，
![image](https://github.com/user-attachments/assets/6b270f2a-ac3d-4db0-9e25-cf54557af1d1)

**Comment by houxinlin** [comment]
修复了，正则问题，可以入群安装新版本
