### ISSUE TITLE
某些rest接口出现无法正常跳转问题，即使手动配置请求trace功能不生效，并没有被cool request拦截代理

### ISSUE THREAD

**Issue by WECENG** [houxinlin/cool-request#133]
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:209)
	at java.base/java.util.ImmutableCollections$List12.<init>(ImmutableCollections.java:556)
	at java.base/java.util.List.of(List.java:812)
	at com.cool.request.common.param.ParameterDescriptionUtils.addParameterToMap(ParameterDescriptionUtils.java:147)
	at com.cool.request.common.param.ParameterDescriptionUtils.buildJSONValue(ParameterDescriptionUtils.java:134)
	at com.cool.request.common.param.ParameterDescriptionUtils.addParameterToMap(ParameterDescriptionUtils.java:147)
	at com.cool.request.common.param.ParameterDescriptionUtils.buildJSONValue(ParameterDescriptionUtils.java:134)
	at com.cool.request.common.param.ParameterDescriptionUtils.addParameterToMap(ParameterDescriptionUtils.java:147)
	at com.cool.request.common.param.ParameterDescriptionUtils.buildJSONValue(ParameterDescriptionUtils.java:134)
	at com.cool.request.common.param.ParameterDescriptionUtils.addParameterToMap(ParameterDescriptionUtils.java:144)
	at com.cool.request.common.param.ParameterDescriptionUtils.buildJSONValue(ParameterDescriptionUtils.java:134)
	at com.cool.request.common.param.ParameterDescriptionUtils.getJSONGuessBody(ParameterDescriptionUtils.java:36)
	at com.cool.request.lib.springmvc.ParameterDescriptionGuessBody.toTextBody(ParameterDescriptionGuessBody.java:27)
	at com.cool.request.view.main.HTTPRequestParamPanel.createDefaultRequestCache(HTTPRequestParamPanel.java:615)
	at com.cool.request.view.main.HTTPRequestParamPanel.loadControllerInfo(HTTPRequestParamPanel.java:521)
	at com.cool.request.view.main.HTTPRequestParamPanel.loadControllerInfoWrapper(HTTPRequestParamPanel.java:487)
	at com.cool.request.view.main.HTTPRequestParamPanel.runLoadControllerInfoOnMain(HTTPRequestParamPanel.java:480)
	at com.cool.request.view.main.MainBottomRequestContainer.controllerChoose(MainBottomRequestContainer.java:124)
	at com.cool.request.view.component.MainHTTPContainer.onComponentChoose(MainHTTPContainer.java:222)
	at com.cool.request.view.component.MainHTTPContainer.attachViewData(MainHTTPContainer.java:212)
	at com.cool.request.view.MultiTabMainBottomHTTPContainer.addNewTab(MultiTabMainBottomHTTPContainer.java:158)
	at com.cool.request.view.MultiTabMainBottomHTTPContainer.attachViewDataWithMultiTab(MultiTabMainBottomHTTPContainer.java:226)
	at com.cool.request.view.MultiTabMainBottomHTTPContainer.attachViewData(MultiTabMainBottomHTTPContainer.java:179)
	at com.cool.request.view.DebugContainerAdapterPage.attachViewData(DebugContainerAdapterPage.java:125)
	at com.cool.request.view.main.MainTopTreeView$2.mouseClicked(MainTopTreeView.java:290)
	at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:278)
	at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:277)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6660)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3385)
	at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:434)
	at java.desktop/java.awt.Component.processEvent(Component.java:6422)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4969)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4592)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4524)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2809)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:794)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:766)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:635)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:580)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:75)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:67)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:580)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:355)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:114)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:848)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:391)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by houxinlin** [comment]
方便看下参数吗

**Comment by WECENG** [comment]
![image](https://github.com/user-attachments/assets/7934b9d4-9545-4c12-93b3-fedca3eabf80)
![image](https://github.com/user-attachments/assets/5e7bf912-7e5c-4719-9adb-ebcc85e4b6a6)
![image](https://github.com/user-attachments/assets/f6bc4cd5-680e-4237-9f2d-15176fdf3075)
![image](https://github.com/user-attachments/assets/29fbc012-d341-4b37-a216-5fd0ca8a9faa)
初步验证，参数存在递归属性导致

**Comment by WECENG** [comment]
![image](https://github.com/user-attachments/assets/25043dfc-9617-470c-827d-f032af187b0e)
找到具体原因了，因为参数List<BigDecimal>导致的

**Comment by houxinlin** [comment]
好的，我也复现了，等下个版本修复，感谢
