### ISSUE TITLE
Bean definition is abstract 异常

### ISSUE THREAD

**Issue by liangweidonggood** [houxinlin/cool-request#39]
项目里用到了ureport

	<bean id="ureport.props" class="com.bstek.ureport.UReportPropertyPlaceholderConfigurer" abstract="true">
		<property name="ignoreUnresolvablePlaceholders" value="true"></property>
	</bean>
启动时报错
Exception in thread "Thread-44" org.springframework.beans.factory.BeanIsAbstractException: Error creating bean with name 'ureport.props': Bean definition is abstract
	at org.springframework.beans.factory.support.AbstractBeanFactory.checkMergedBeanDefinition(AbstractBeanFactory.java:1478)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1154)
	at com.hxl.plugin.scheduledinvokestarter.components.xxljob.XXJJobComponentDataHandler.lambda$refresh$0(XXJJobComponentDataHandler.java:54)
	at java.lang.Thread.run(Thread.java:750)

把插件禁了才不报错

**Comment by houxinlin** [comment]
有点奇怪，在设置中禁用第一个选项就可以了

**Comment by houxinlin** [comment]
有点奇怪，能加个联系方式吗

**Comment by liangweidonggood** [comment]
微信号：q80298116

**Comment by liangweidonggood** [comment]
![1](https://github.com/houxinlin/cool-request/assets/6304507/2aee859d-f362-4cf5-aed5-5926e944516f)
把这个动态刷新关了确实不报错了
