### ISSUE TITLE
com.intellij.diagnostic.PluginException

### ISSUE THREAD

**Issue by muzizi727** [houxinlin/cool-request#63]
idea版本：2024.1
插件版本：2024.7.1
打开侧边栏就会有报错
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.cool.request.action.actions.CoolRequestAnAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.hxl.plugin.cool-request]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)

**Comment by houxinlin** [comment]
这个错不影响使用，是个兼容性问题

**Comment by muzizi727** [comment]
但是每次打开都有提示，改动大吗？有计划优化吗？

**Comment by houxinlin** [comment]
这个只能提高最低版本兼容才能解决，现在最低兼容2020版本，计划后半年升级，你可以进群，发你一个单独解决这个错误的版本

**Comment by muzizi727** [comment]
好的，谢谢，这个单独的版本后续可以升级吗？

**Comment by houxinlin** [comment]
后续不可以，只能安装通过我单独为高版本的兼容的版本

**Comment by muzizi727** [comment]
好的，感谢~
