### ISSUE TITLE
非web项目启动时，启动项目后，插件报错会导致项目异常，

### ISSUE THREAD

**Issue by randeexiong** [houxinlin/cool-request#73]
Exception in thread "Thread-4" java.lang.NoClassDefFoundError: org/springframework/web/multipart/MultipartFile
	at com.cool.request.components.method.parameter.ParameterConverters$PrimitiveParameterConverter.<init>(ParameterConverters.java:193)
	at com.cool.request.components.method.ParameterConvertManager.<init>(ParameterConvertManager.java:16)
	at com.cool.request.components.method.MethodComponentDataHandler.<init>(MethodComponentDataHandler.java:30)
	at com.cool.request.components.method.MethodComponentSupport.start(MethodComponentSupport.java:17)
	at com.cool.request.components.ComponentLoader$LoaderThread.run(ComponentLoader.java:102)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: org.springframework.web.multipart.MultipartFile
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 6 more

**Comment by houxinlin** [comment]
铁子，发生什么事了，为何关闭，确实存在这个问题

**Comment by randeexiong** [comment]
后面我发现在设置里面，把动态刷新的选项关闭了还能用，就关闭这个议题了

**Comment by randeexiong** [comment]
能不能动态判断下？如果没有引用相关包包，插件就不去检索

**Comment by houxinlin** [comment]
月底新版本会修复的
